name: Terraform CI/CD
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" -var "openai_api_key=${{ secrets.OPENAI_API_KEY }}" -var "pinecone_api_key=${{ secrets.PINECONE_API_KEY }}"
        working-directory: infra